### ISSUE TITLE
Github Actions set-env command is deprecated

### ISSUE THREAD

**Issue by wpoehlm** [Sage-Bionetworks-Workflows/cwl-workflow-template#4]
An Environment file must now be used instead of the set-env command for CI to run successfully. An example can be found here:

https://github.com/Sage-Bionetworks-Workflows/dockstore-tool-template/pull/23

**Comment by tthyer** [comment]
set-env was not necessary for this repo and has been removed. The update occurred in commit d8ba692888b31e12ec69e7c5be095798e05eb5de.
